import time
import os
from dataclasses import dataclass
import requests

# Ensure you have your model config dataclass available from Phase 1, Step 1
from registry import ModelConfig

@dataclass
class Response:
    output_text: str          # The raw textual completion generated by the model
    input_tokens: int         # Exact number of prompt tokens processed
    output_tokens: int        # Exact number of completion tokens generated
    latency_seconds: float    # High-precision round-trip wall-clock time
    cost: float               # Calculated total request cost in absolute USD
    model_id: str             # The exact model identifier that fulfilled the request
