import json
import re
from dataclasses import dataclass
from typing import List, Optional

@dataclass
class VerificationResult:
    passed: bool
    score: float
    reason: str
    task_type: str

class QualityThresholds:
    """
    Defines strict boundaries for what constitutes a 'successful' cheap model routing.
    Compares the cheap model's output against the expensive Tier 3 model's output.
    """

    # --- CONSTANT THRESHOLDS ---
    MIN_SUMMARY_SCORE = 4.0  # Out of 5.0

    @staticmethod
    def verify_extraction(cheap_output: str, expensive_output: str) -> VerificationResult:
        """
        EXTRACTION: Did the cheap model capture all the key fields that the expensive model found?
        Logic: Attempts to parse JSON from both. The cheap model passes if it contains 
        every top-level key present in the expensive model's output.
        """
        try:
            # Simple heuristic to extract JSON blocks if wrapped in markdown
            cheap_json_str = re.search(r'\{.*\}', cheap_output.replace('\n', ''))
            exp_json_str = re.search(r'\{.*\}', expensive_output.replace('\n', ''))
            
            if not cheap_json_str or not exp_json_str:
                return VerificationResult(False, 0.0, "Failed to parse JSON from outputs.", "extraction")

            cheap_dict = json.loads(cheap_json_str.group())
            exp_dict = json.loads(exp_json_str.group())

            missing_keys = [key for key in exp_dict.keys() if key not in cheap_dict]
            
            if missing_keys:
                return VerificationResult(
                    passed=False, 
                    score=0.0, 
                    reason=f"Missing critical extraction keys: {missing_keys}", 
                    task_type="extraction"
                )
                
            return VerificationResult(True, 1.0, "All required keys extracted successfully.", "extraction")
            
        except json.JSONDecodeError:
            return VerificationResult(False, 0.0, "Invalid JSON structure generated.", "extraction")

    @staticmethod
    def verify_classification(cheap_output: str, expensive_output: str) -> VerificationResult:
        """
        CLASSIFICATION: Does the label agree exactly with what GPT-4o (expensive) returned?
        Logic: Exact or normalized substring match.
        """
        # Normalize text: lowercase, strip punctuation and whitespace
        clean_cheap = re.sub(r'[^a-z0-9]', '', cheap_output.lower())
        clean_exp = re.sub(r'[^a-z0-9]', '', expensive_output.lower())
        
        # Check if the expensive model's exact label exists in the cheap model's output
        if clean_exp in clean_cheap or clean_cheap in clean_exp:
            return VerificationResult(True, 1.0, "Classification labels align perfectly.", "classification")
            
        return VerificationResult(
            passed=False, 
            score=0.0, 
            reason=f"Label mismatch. Expected semantic match with: '{expensive_output}'", 
            task_type="classification"
        )

    @staticmethod
    def build_llm_judge_prompt(original_prompt: str, cheap_output: str) -> str:
        """
        SUMMARIZATION: Builds the prompt for the Tier 3 model to act as an impartial judge.
        The verifier loop will send this to GPT-4o to get a score from 1 to 5.
        """
        return f"""
        You are an impartial Quality Assurance AI. 
        Your task is to evaluate a summarization generated by a cheaper, faster model.
        
        ORIGINAL TEXT/PROMPT:
        {original_prompt}
        
        GENERATED SUMMARY:
        {cheap_output}
        
        Evaluate the summary based on accuracy, conciseness, and preservation of core intent.
        Score it from 1 to 5, where:
        1 = Completely inaccurate or hallucinates facts.
        3 = Misses key details but is technically true.
        4 = Good summary, captures main points.
        5 = Perfect, concise, and accurate summary.
        
        Return ONLY a valid JSON object in this exact format, with no markdown formatting:
        {{"score": 4, "reason": "short explanation"}}
        """
